<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pretext.Wpf\Pretext.Wpf.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="TestData/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
